services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-llm-service
    ports:
      - "6437:5432"
    environment:
      POSTGRES_DB: llm_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_llm_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d llm_service" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_llm_data:
